{% set version = "2.0.9" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-biasedurn
  version: {{ version|replace("-", "_") }}

source:
  fn: BiasedUrn_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/BiasedUrn_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/BiasedUrn/BiasedUrn_{{ version }}.tar.gz
  sha256: bac62bbbc3e2417772f8784996a6c2d0857adb42e86e46b1a9703b187a406b09

build:
  merge_build_host: true  # [win]
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('BiasedUrn')"           # [not win]
    - "\"%R%\" -e \"library('BiasedUrn')\""  # [win]

about:
  home: http://www.agner.org/random/ http://www.r-project.org
  license: GPL-3
  summary: Statistical models of biased sampling in the form of  univariate and multivariate noncentral hypergeometric distributions,  including Wallenius' noncentral hypergeometric distribution and Fisher's noncentral hypergeometric distribution  (also called extended hypergeometric distribution).   See vignette("UrnTheory")
    for explanation of these distributions.
  license_family: GPL3
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
