# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_r_base3.4.1target_platformosx-64
    - CONFIG=osx_r_base3.5.1target_platformosx-64

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jsLLAHl7FbTgywHN5c4HjzkShdKfdoW4b5pqg5BLGp6i/9QQS7Im0/ujI3L5T9CnEtCw5agzn80YPMNBz78ylicsUMpPEqCoMsNW8YCOjh2OL4TIvr2tYFlgr0SUjWa6BVdjs/e1vaE/XrqQ+DoAJcdX+08mjbfftwuRHYYVLO0KJpAOTgf0YjjhSxci7Eulwrg5kK1cQagtmXCeMdMMowE1PDqt67t+c2AumTke7KSvw1Xryk6RH7t3LE3jYL6y7uEyz8L7Uo/7LGtptqUxQ/PRnrjOrzi3NHNfDchTVx/Xb+exAvzUG2+f77V6WDjDIt8ZWwccSHCWB1rsVr6gfcWQ6W4Xcmj3gJFlzJmY/L8t6pMq2FmdU6IStZrM+h0PhIFGbgdA+BSMh5T8TjwEuTGhOFRbxSKceMloQWGYLR+1qraDg3Q87pOvNyMSzNhw85JKCQoIs7APYn5IcethpLYhEiyyxCEnnZBiZoR8N6d1/+atonthq+HFaG+F2b08/7q1++xVLKTH9e8lVbMZ7D2H7YY4mFC1Z1SZH2kDVr7Pzas4HUIn/0ipnsWonyY+FGqncrx3/7i4E3bez2ElaKAUa8xnkEVrgGmtS+hU6477hNDRA+jhKqBYafQ3d1EHGaoVDTUw6HcivjOWbjvS1bRx51ZAQ4dtOijZzkFoA6Y="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
