appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: jsLLAHl7FbTgywHN5c4HjzkShdKfdoW4b5pqg5BLGp6i/9QQS7Im0/ujI3L5T9CnEtCw5agzn80YPMNBz78ylicsUMpPEqCoMsNW8YCOjh2OL4TIvr2tYFlgr0SUjWa6BVdjs/e1vaE/XrqQ+DoAJcdX+08mjbfftwuRHYYVLO0KJpAOTgf0YjjhSxci7Eulwrg5kK1cQagtmXCeMdMMowE1PDqt67t+c2AumTke7KSvw1Xryk6RH7t3LE3jYL6y7uEyz8L7Uo/7LGtptqUxQ/PRnrjOrzi3NHNfDchTVx/Xb+exAvzUG2+f77V6WDjDIt8ZWwccSHCWB1rsVr6gfcWQ6W4Xcmj3gJFlzJmY/L8t6pMq2FmdU6IStZrM+h0PhIFGbgdA+BSMh5T8TjwEuTGhOFRbxSKceMloQWGYLR+1qraDg3Q87pOvNyMSzNhw85JKCQoIs7APYn5IcethpLYhEiyyxCEnnZBiZoR8N6d1/+atonthq+HFaG+F2b08/7q1++xVLKTH9e8lVbMZ7D2H7YY4mFC1Z1SZH2kDVr7Pzas4HUIn/0ipnsWonyY+FGqncrx3/7i4E3bez2ElaKAUa8xnkEVrgGmtS+hU6477hNDRA+jhKqBYafQ3d1EHGaoVDTUw6HcivjOWbjvS1bRx51ZAQ4dtOijZzkFoA6Y=
conda_forge_output_validation: true
