travis:
  secure:
    BINSTAR_TOKEN: Y13rMFTiJIDEpcIDhsKJn0zFCSaxhJoIdVcU/tGjlOVZm1qc+fJ/Pb4wLU1dlvbZv4pooJhj9s44PoBSTCZU24Q28KtrsZ9Pe1P8M1jZQIJyhvpMO0FlZ2a/sltzESYNL5ItF5sdv+rZoUKVXURk3lRsfY/KrbcF5FUlUCI5F7CxMaRprhmGGS5+pfS/0/WCpW+9xEBY78JuMs6u5twzskbY/y5a45YMPvRu8Zs/BhN0LZ+osOP+McKZYQG7Uv+al0RZNdiao1yHxR+C2DW07y8NfJrTADCGBGtHzGMlVF8EAMQqyzgkJKjnr0kBT3xOkES3h2S7TjMOMFcX6XyuUmg+pnHgGRtukVQJqrpFAxhBm2WUmzuqBR+lh8QQZI5cC0eeOjBwbOEdf6R6sz0B/iaCocin4TpucbWZFoQWijhA+A5beKTB50zySpbPlVyJeZJL06Ox5XBAUMPOy7zhWjUSEN2trLhrDbMCejvt4P13hbGLBnIfUXI4/B/0HI9M7QJCVx0bte/Mxlp18bsbOdD4991RN6WZS2olVMcfS9J8WE0gyeWlPBYdgT16IFsrJgsEM3R3JWtwyWoZpWEKfkH0sCPmzaI0yo0S5OKiYaSByWeKeriodaWsfVoYT8PJ+190Oveer4psor6RcGcVTNHaFSbAZELmjh3b/ni7c7U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
